"""Initial Migration

Revision ID: 7a510242728c
Revises: 
Create Date: 2021-01-15 08:09:53.066149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a510242728c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistants', 'initial',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=6),
               nullable=True)
    op.alter_column('assistants', 'leader_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)
    op.alter_column('assistants', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('assistants', 'period_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)
    op.drop_index('assistants_leader_id_foreign', table_name='assistants')
    op.drop_index('assistants_period_id_foreign', table_name='assistants')
    op.create_unique_constraint(None, 'assistants', ['initial'])
    op.create_foreign_key(None, 'assistants', 'leaders', ['leader_id'], ['id'])
    op.create_foreign_key(None, 'assistants', 'periods', ['period_id'], ['id'])
    op.alter_column('leaders', 'initial',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=6),
               nullable=True)
    op.alter_column('leaders', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('leaders', 'period_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)
    op.create_unique_constraint(None, 'leaders', ['initial'])
    op.create_foreign_key(None, 'leaders', 'periods', ['period_id'], ['id'])
    op.alter_column('periods', 'description',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('periods', 'end',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('periods', 'start',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('periods', 'start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('periods', 'end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('periods', 'description',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.drop_constraint(None, 'leaders', type_='foreignkey')
    op.drop_constraint(None, 'leaders', type_='unique')
    op.alter_column('leaders', 'period_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)
    op.alter_column('leaders', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('leaders', 'initial',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=6),
               nullable=False)
    op.drop_constraint(None, 'assistants', type_='foreignkey')
    op.drop_constraint(None, 'assistants', type_='foreignkey')
    op.drop_constraint(None, 'assistants', type_='unique')
    op.create_index('assistants_period_id_foreign', 'assistants', ['period_id'], unique=False)
    op.create_index('assistants_leader_id_foreign', 'assistants', ['leader_id'], unique=False)
    op.alter_column('assistants', 'period_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)
    op.alter_column('assistants', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('assistants', 'leader_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)
    op.alter_column('assistants', 'initial',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=6),
               nullable=False)
    # ### end Alembic commands ###
